#!/bin/bash

# Check that empty-expect is installed and install if not
dpkg --get-selections | grep empty
rc=$?
if ! [ $rc -eq 0 ]; then
  apt-get install -y empty-expect
fi

# Check that firewall is in /etc/hosts
grep 192.168.0.2 /etc/hosts
rc=$?
if ! [ $rc -eq 0 ]; then
  echo -e "\n192.168.0.2\tfirewall" >> /etc/hosts
fi

# Get hostname for firewall
__FWHOSTNAME__=`awk '/192.168.0.2/ { print $2 }' /etc/hosts`

# Copy SSH key to firewall
empty -f -i in.fifo -o out.fifo -p vyosconfig.pid -L vyosconfig.log ssh-copy-id -o StrictHostKeyChecking=no vyos@$__FWHOSTNAME__
empty -w -i out.fifo -o in.fifo "assword" "vyos\n"

# Remove empty artifacts
rm -f in.fifo out.fifo vyosconfig.pid vyosconfig.log

# Login into firewall
empty -f -i input.fifo -o output.fifo -p vyosconfig.pid -L vyosconfig.log ssh -o StrictHostKeyChecking=no vyos@$__FWHOSTNAME__

# Enter configuration mode
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "conf\n"

# Configure IPv4 addresses for firewall devices
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.2/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.3/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.4/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.5/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.6/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.7/24\n"

# Configure IPv4 addresses for loadbalancer devices
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.249/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.250/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.251/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.252/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.253/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.0.254/24\n"

# Configure IPv4 addresses for host nodes
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.101/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.102/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.103/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.104/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.105/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.106/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.107/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.108/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.109/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.110/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.111/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.112/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.113/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.114/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.115/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.116/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.117/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.118/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.119/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.120/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.121/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.122/24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.239.123/24\n"

# Configure IPv4 addresses for floating IPs
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.2/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.3/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.4/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.5/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.6/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.7/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.8/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.9/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.10/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.11/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.12/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.13/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.14/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.15/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.16/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.17/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.18/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.19/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.20/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.21/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.22/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.23/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.24/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.25/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.26/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.27/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.28/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.29/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.30/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.31/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.32/22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth0 address 192.168.240.33/22\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set interfaces ethernet eth1 vif 100 address 172.24.96.1/22\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

# Configure destination NAT translation public node to private node IPv4 address
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 101\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 101 destination address 192.168.239.101\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 101 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 101 translation address 10.239.0.101\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 102\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 102 destination address 192.168.239.102\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 102 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 102 translation address 10.239.0.102\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 103\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 103 destination address 192.168.239.103\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 103 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 103 translation address 10.239.0.103\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 104\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 104 destination address 192.168.239.104\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 104 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 104 translation address 10.239.0.104\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 105\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 105 destination address 192.168.239.105\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 105 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 105 translation address 10.239.0.105\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 106\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 106 destination address 192.168.239.106\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 106 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 106 translation address 10.239.0.106\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 107\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 107 destination address 192.168.239.107\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 107 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 107 translation address 10.239.0.107\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 108\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 108 destination address 192.168.239.108\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 108 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 108 translation address 10.239.0.108\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 109\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 109 destination address 192.168.239.109\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 109 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 109 translation address 10.239.0.109\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 110\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 110 destination address 192.168.239.110\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 110 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 110 translation address 10.239.0.110\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 111\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 111 destination address 192.168.239.111\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 111 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 111 translation address 10.239.0.111\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 112\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 112 destination address 192.168.239.112\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 112 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 112 translation address 10.239.0.112\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 113\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 113 destination address 192.168.239.113\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 113 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 113 translation address 10.239.0.113\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 114\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 114 destination address 192.168.239.114\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 114 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 114 translation address 10.239.0.114\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 115\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 115 destination address 192.168.239.115\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 115 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 115 translation address 10.239.0.115\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

# Configure destination NAT translation public floating to private floating IPv4 address
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 301\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 301 destination address 192.168.240.2\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 301 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 301 translation address 10.240.0.2\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 302\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 302 destination address 192.168.240.3\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 302 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 302 translation address 10.240.0.3\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 303\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 303 destination address 192.168.240.4\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 303 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 303 translation address 10.240.0.4\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 304\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 304 destination address 192.168.240.5\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 304 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 304 translation address 10.240.0.5\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 305\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 305 destination address 192.168.240.6\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 305 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 305 translation address 10.240.0.6\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 306\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 306 destination address 192.168.240.7\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 306 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 306 translation address 10.240.0.7\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 307\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 307 destination address 192.168.240.8\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 307 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 307 translation address 10.240.0.8\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 308\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 308 destination address 192.168.240.9\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 308 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 308 translation address 10.240.0.9\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 309\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 309 destination address 192.168.240.10\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 309 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 309 translation address 10.240.0.10\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 310\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 310 destination address 192.168.240.11\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 310 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 310 translation address 10.240.0.11\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 311\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 311 destination address 192.168.240.12\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 311 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 311 translation address 10.240.0.12\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 312\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 312 destination address 192.168.240.13\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 312 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 312 translation address 10.240.0.13\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 313\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 313 destination address 192.168.240.14\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 313 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 313 translation address 10.240.0.14\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 314\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 314 destination address 192.168.240.15\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 314 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 314 translation address 10.240.0.15\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 315\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 315 destination address 192.168.240.16\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 315 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 315 translation address 10.240.0.16\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 316\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 316 destination address 192.168.240.17\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 316 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 316 translation address 10.240.0.17\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 317\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 317 destination address 192.168.240.18\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 317 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 317 translation address 10.240.0.18\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 318\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 318 destination address 192.168.240.19\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 318 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 318 translation address 10.240.0.19\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 319\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 319 destination address 192.168.240.20\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 319 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 319 translation address 10.240.0.20\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 320\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 320 destination address 192.168.240.21\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 320 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 320 translation address 10.240.0.21\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 321\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 321 destination address 192.168.240.22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 321 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 321 translation address 10.240.0.22\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 322\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 322 destination address 192.168.240.23\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 322 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 322 translation address 10.240.0.23\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 323\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 323 destination address 192.168.240.24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 323 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 323 translation address 10.240.0.24\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 324\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 324 destination address 192.168.240.25\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 324 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 324 translation address 10.240.0.25\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 325\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 325 destination address 192.168.240.26\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 325 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 325 translation address 10.240.0.26\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 326\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 326 destination address 192.168.240.27\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 326 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 326 translation address 10.240.0.27\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 327\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 327 destination address 192.168.240.28\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 327 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 327 translation address 10.240.0.28\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 328\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 328 destination address 192.168.240.29\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 328 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 328 translation address 10.240.0.29\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 329\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 329 destination address 192.168.240.30\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 329 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 329 translation address 10.240.0.30\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 330\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 330 destination address 192.168.240.31\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 330 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 330 translation address 10.240.0.31\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 331\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 331 destination address 192.168.240.32\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 331 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 331 translation address 10.240.0.32\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 332\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 332 destination address 192.168.240.33\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 332 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 332 translation address 10.240.0.33\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

# Configure destination NAT translation public loadbalancer to private loadbalancer IPv4 address
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 500\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 500 destination address 192.168.0.249\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 500 inbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat destination rule 500 translation address 172.29.236.100\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

# Configure source NAT translation private node to public node IPv4 address
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 201\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 201 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 201 source address 10.239.0.101\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 201 translation address 192.168.239.101\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 202\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 202 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 202 source address 10.239.0.102\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 202 translation address 192.168.239.102\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 203\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 203 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 203 source address 10.239.0.103\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 203 translation address 192.168.239.103\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 204\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 204 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 204 source address 10.239.0.104\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 204 translation address 192.168.239.104\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 205\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 205 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 205 source address 10.239.0.105\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 205 translation address 192.168.239.105\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 206\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 206 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 206 source address 10.239.0.106\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 206 translation address 192.168.239.106\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 207\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 207 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 207 source address 10.239.0.107\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 207 translation address 192.168.239.107\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 208\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 208 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 208 source address 10.239.0.108\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 208 translation address 192.168.239.108\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 209\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 209 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 209 source address 10.239.0.109\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 209 translation address 192.168.239.109\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 210\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 210 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 210 source address 10.239.0.110\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 210 translation address 192.168.239.110\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 211\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 211 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 211 source address 10.239.0.111\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 211 translation address 192.168.239.111\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 212\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 212 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 212 source address 10.239.0.112\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 212 translation address 192.168.239.112\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 213\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 213 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 213 source address 10.239.0.113\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 213 translation address 192.168.239.113\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 214\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 214 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 214 source address 10.239.0.114\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 214 translation address 192.168.239.114\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 215\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 215 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 215 source address 10.239.0.115\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 215 translation address 192.168.239.115\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

# Configure source NAT translation private loadbalancer to public loadbalancer IPv4 address
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 550\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 550 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 550 source address 172.24.96.249\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 550 translation address 192.168.0.249\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

# Configure source NAT translation private floating to public floating IPv4 address
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 401\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 401 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 401 source address 10.240.0.2\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 401 translation address 192.168.240.2\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 402\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 402 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 402 source address 10.240.0.3\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 402 translation address 192.168.240.3\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 403\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 403 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 403 source address 10.240.0.4\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 403 translation address 192.168.240.4\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 404\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 404 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 404 source address 10.240.0.5\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 404 translation address 192.168.240.5\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 405\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 405 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 405 source address 10.240.0.6\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 405 translation address 192.168.240.6\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 406\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 406 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 406 source address 10.240.0.7\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 406 translation address 192.168.240.7\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 407\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 407 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 407 source address 10.240.0.8\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 407 translation address 192.168.240.8\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 408\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 408 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 408 source address 10.240.0.9\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 408 translation address 192.168.240.9\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 409\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 409 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 409 source address 10.240.0.10\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 409 translation address 192.168.240.10\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 410\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 410 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 410 source address 10.240.0.11\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 410 translation address 192.168.240.11\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 411\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 411 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 411 source address 10.240.0.12\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 411 translation address 192.168.240.12\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 412\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 412 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 412 source address 10.240.0.13\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 412 translation address 192.168.240.13\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 413\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 413 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 413 source address 10.240.0.14\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 413 translation address 192.168.240.14\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 414\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 414 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 414 source address 10.240.0.15\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 414 translation address 192.168.240.15\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 415\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 415 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 415 source address 10.240.0.16\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 415 translation address 192.168.240.16\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 416\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 416 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 416 source address 10.240.0.17\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 416 translation address 192.168.240.17\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 417\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 417 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 417 source address 10.240.0.18\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 417 translation address 192.168.240.18\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 418\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 418 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 418 source address 10.240.0.19\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 418 translation address 192.168.240.19\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 419\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 419 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 419 source address 10.240.0.20\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 419 translation address 192.168.240.20\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 420\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 420 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 420 source address 10.240.0.21\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 420 translation address 192.168.240.21\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 421\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 421 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 421 source address 10.240.0.22\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 421 translation address 192.168.240.22\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 422\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 422 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 422 source address 10.240.0.23\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 422 translation address 192.168.240.23\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 423\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 423 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 423 source address 10.240.0.24\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 423 translation address 192.168.240.24\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 424\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 424 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 424 source address 10.240.0.25\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 424 translation address 192.168.240.25\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 425\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 425 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 425 source address 10.240.0.26\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 425 translation address 192.168.240.26\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 426\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 426 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 426 source address 10.240.0.27\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 426 translation address 192.168.240.27\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 427\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 427 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 427 source address 10.240.0.28\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 427 translation address 192.168.240.28\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 428\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 428 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 428 source address 10.240.0.29\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 428 translation address 192.168.240.29\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 429\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 429 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 429 source address 10.240.0.30\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 429 translation address 192.168.240.30\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 430\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 430 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 430 source address 10.240.0.31\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 430 translation address 192.168.240.31\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 431\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 431 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 431 source address 10.240.0.32\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 431 translation address 192.168.240.32\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 432\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 432 outbound-interface eth0\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 432 source address 10.240.0.33\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set nat source rule 432 translation address 192.168.240.33\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set protocols static route 0.0.0.0/0 next-hop 192.168.0.1\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set protocols static route 10.239.0.0/22 next-hop 172.24.96.249\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set protocols static route 10.240.0.0/22 next-hop 172.24.96.249\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set protocols static route 172.29.236.0/22 next-hop 172.24.96.249\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set protocols static route 172.29.240.0/22 next-hop 172.24.96.249\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set protocols static route 172.29.244.0/22 next-hop 172.24.96.249\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service ssh allow-root\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service ssh disable-host-validation\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service ssh listen-address 192.168.0.2\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service ssh port 22\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"

empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set system domain-name firewal.local\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set system host-name firewall\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service dns forwarding cache-size 1000\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service dns forwarding listen-on eth1.100\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service dns forwarding name-server 69.20.0.164\n"
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "set service dns forwarding name-server 69.20.0.196\n"

# Commit changes to firewall runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "commit\n"
# Save runtime configuration
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "save config\n"
# Exit configuration mode
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "exit\n"
# Logout of the firewall
empty -w -i output.fifo -o input.fifo "vyos\@vyos" "exit\n"

# Remove empty artifacts
rm input.fifo output.fifo vyosconfig.pid vyosconfig.log
