---
- name: Prepare OnMetal Host
  hosts: all
  remote_user: root
  tasks:
    - name: "Install preliminary packages"
      apt:
        name: git
        update_cache: yes
        state: latest
        autoremove: yes
      tags:
        - always

    - name: "Clone Github Repository"
      git:
        repo: http://github.com/mrhillsman/rpcops-onmetal-labconfigurator
        accept_hostkey: yes
        clone: yes
        dest: /root/rpcops-onmetal-labconfigurator
        recursive: yes
        version: master
      tags:
        - always
#acpifixed file exists, need to create a check for it here and run usage on when it does not exist
#    - name: "Run CPU Usage Check"
#      command: bash /root/rpcops-onmetal-labconfigurator/rpcops-host-setup
#      ignore_errors: yes
#      tags:
#        - always

#    - name: Wait for server restart
#      local_action:
#        module: wait_for
#        host: "{{ inventory_hostname }}"
#        port: 22
#        state: started
#        delay: 5
#        timeout: 30
#      tags:
#        - always
    - name: Wait for server restart
      pause:
        minutes: 4

    - name: "Run Host Setup"
      command: bash /root/rpcops-onmetal-labconfigurator/rpcops-host-setup
      async: 3600
      poll: 10
      tags:
        - always