---

- name: "Create Lab Environment"
  hosts: all
  remote_user: root

  tasks:
    - name: "Spawn Lab"
      command: bash /root/rpcops-onmetal-labconfigurator/rpcops-lab-setup
      async: 3600
      poll: 10
      ignore_errors: yes
      tags:
        - always

    - name: "Prepare Cinder Storage"
      command: ansible-playbook -i inventory playbooks/cinder-disks-prepare.yml chdir=/root/rpcops-onmetal-labconfigurator
      tags:
        - always

    - name: "Prepare Swift Storage"
      command: ansible-playbook -i inventory playbooks/swift-disks-prepare.yml chdir=/root/rpcops-onmetal-labconfigurator
      tags:
        - always

    - name: "Prepare VMs for OpenStack-Ansible"
      command: ansible-playbook -i inventory playbooks/pre-openstack-install.yml chdir=/root/rpcops-onmetal-labconfigurator
      tags:
        - always