#!/bin/bash

# Woah there, not called destroyer for nothing...
# Will do the following:
# all nodes (VMs)
# - delete virtual disk
# - undefine node
# cobbler
# - delete profiles
# - delete systems

cd /var/lib/libvirt/images

# Force shutdown and remove all instances
for i in `virsh list --all --name|awk '/infra|compute|storage|cinder|ceph|swift|logger/ { print }'`; do virsh destroy $i; done;
for i in `virsh list --all --name|awk '/infra|compute|storage|cinder|ceph|swift|logger/ { print }'`; do virsh undefine $i; done;

# Delete all disks
find . -regextype posix-extended -iregex '.*(infra|compute|storage|cinder|ceph|swift|logger).*' -delete