#!/bin/bash

# Set NSIP
echo 'set ns config -IPAddress 10.5.0.4 -netmask 255.255.255.0'

# Enable LoadBalancing and SSL Offloading
echo 'enable ns feature LB SSL'

# Enable VPX sensible defaults for lab
echo 'enable ns mode FR L3 MBF Edge USNIP PMTUD'
echo 'set system user nsroot 1704899a34785fea0e50b54a6d1f705a960a0eda3e580149b -encrypted'
echo 'set ns hostName loadbalancer'
echo 'add dns nameServer 172.24.96.1'

# Configure network interfaces
echo 'set interface 0/1 -haMonitor OFF -throughput 0 -bandwidthHigh 0 -bandwidthNormal 0 -intftype "KVM Virtio" -ifnum 0/1'
echo 'set interface 1/1 -haMonitor OFF -throughput 0 -bandwidthHigh 0 -bandwidthNormal 0 -intftype "KVM Virtio" -ifnum 1/1'
echo 'set interface 1/2 -haMonitor OFF -throughput 0 -bandwidthHigh 0 -bandwidthNormal 0 -intftype "KVM Virtio" -ifnum 1/2'
echo 'set interface 1/3 -haMonitor OFF -throughput 0 -bandwidthHigh 0 -bandwidthNormal 0 -intftype "KVM Virtio" -ifnum 1/3'
echo 'set interface 1/4 -haMonitor OFF -throughput 0 -bandwidthHigh 0 -bandwidthNormal 0 -intftype "KVM Virtio" -ifnum 1/4'
echo 'set interface LO/1 -haMonitor OFF -throughput 0 -bandwidthHigh 0 -bandwidthNormal 0 -intftype Loopback -ifnum LO/1'

# Configure VLANS
echo 'add vlan 100 -aliasName FW_LB'
echo 'add vlan 201 -aliasName RPC_HOST'
echo 'add vlan 202 -aliasName RPC_CONTAINER'
echo 'add vlan 205 -aliasName RPC_GATEWAY'

# Configure IP Addresses
echo 'add ns ip 10.239.0.1 255.255.252.0 -vServer DISABLED -gui DISABLED'
echo 'add ns ip 10.240.0.1 255.255.252.0 -vServer DISABLED -gui DISABLED'
echo 'add ns ip 172.29.236.15 255.255.252.0 -vServer DISABLED -gui DISABLED'
echo 'add ns ip 172.29.236.100 255.255.252.0 -type VIP'
echo 'add ns ip 172.24.96.249 255.255.252.0 -vServer DISABLED -gui DISABLED'
echo 'add ns ip 172.24.96.250 255.255.252.0 -type VIP -mgmtAccess ENABLED'

# Bind VLANs to IP addresses
echo 'bind vlan 100 -ifnum 1/1 -tagged'
echo 'bind vlan 100 -IPAddress 172.24.96.249 255.255.252.0'
echo 'bind vlan 201 -ifnum 1/2 -tagged'
echo 'bind vlan 201 -IPAddress 10.239.0.1 255.255.252.0'
echo 'bind vlan 202 -ifnum 1/2 -tagged'
echo 'bind vlan 202 -IPAddress 172.29.236.100 255.255.252.0'
echo 'bind vlan 205 -ifnum 1/3 -tagged'
echo 'bind vlan 205 -IPAddress 10.240.0.1 255.255.252.0'

# Configure static routes
echo 'add route 0.0.0.0 0.0.0.0 172.24.96.1'
echo 'add route 10.5.0.0 255.255.255.0 10.5.0.1'

# Configure servers/services
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name") \($server."ansible_ssh_host")"'|grep container|while read i; do echo "add server ${i}"; done;

# Configure ServiceGroups / Pools
echo 'add serviceGroup RPC_POOL_HORIZON HTTP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 180 -svrTimeout 360 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_HORIZON_SSL HTTP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 180 -svrTimeout 360 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_KEYSTONE_SERVICE TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_GALERA TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_ELASTICSEARCH TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_NEUTRON_SERVER TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_NOVA_API_EC2 TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_HEAT_API TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_CINDER_API TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_KIBANA TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_NOVA_API_METADATA HTTP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 180 -svrTimeout 360 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_NOVA_API_OS_COMPUTE TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_GLANCE_API TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_NOVA_SPICE_CONSOLE HTTP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 180 -svrTimeout 360 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_HEAT_API_CLOUDWATCH TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_HEAT_API_CFN TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_GLANCE_REGISTRY TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_SWIFT HTTP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 180 -svrTimeout 360 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_KEYSTONE_ADMIN TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_KIBANA_SSL TCP -maxClient 0 -maxReq 0 -cip DISABLED -usip NO -useproxyport YES -cltTimeout 9000 -svrTimeout 9000 -CKA NO -TCPB NO -CMP NO'
echo 'add serviceGroup RPC_POOL_REPO HTTP -maxClient 0 -maxReq 0 -cacheable YES -cip DISABLED -usip NO -useproxyport YES -cltTimeout 180 -svrTimeout 360 -CKA NO -TCPB NO -CMP NO -appflowLog DISABLED'

# Bind servers/services to ServiceGroups / Pools
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep horizon|while read i; do echo "bind serviceGroup RPC_POOL_HORIZON ${i} 80"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep horizon|while read i; do echo "bind serviceGroup RPC_POOL_HORIZON_SSL ${i} 443"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep keystone|while read i; do echo "bind serviceGroup RPC_POOL_KEYSTONE_SERVICE ${i} 5000"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep galera|while read i; do echo "bind serviceGroup RPC_POOL_GALERA ${i} 3306"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep elasticsearch|while read i; do echo "bind serviceGroup RPC_POOL_ELASTICSEARCH ${i} 9200"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep neutron_server|while read i; do echo "bind serviceGroup RPC_POOL_NEUTRON_SERVER ${i} 9696"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep nova_api_ec2|while read i; do echo "bind serviceGroup RPC_POOL_NOVA_API_EC2 ${i} 8773"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep heat_apis|while read i; do echo "bind serviceGroup RPC_POOL_HEAT_API ${i} 8004"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep cinder_api|while read i; do echo "bind serviceGroup RPC_POOL_CINDER_API ${i} 8776"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep kibana|while read i; do echo "bind serviceGroup RPC_POOL_KIBANA ${i} 8888"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep nova_api_metadata|while read i; do echo "bind serviceGroup RPC_POOL_NOVA_API_METADATA ${i} 8775"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep nova_api_os_compute|while read i; do echo "bind serviceGroup RPC_POOL_NOVA_API_OS_COMPUTE ${i} 8774"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep glance|while read i; do echo "bind serviceGroup RPC_POOL_GLANCE_API ${i} 9292"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep nova_spice_console|while read i; do echo "bind serviceGroup RPC_POOL_NOVA_SPICE_CONSOLE ${i} 6082"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep heat_apis|while read i; do echo "bind serviceGroup RPC_POOL_HEAT_API_CLOUDWATCH ${i} 8003"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep heat_apis|while read i; do echo "bind serviceGroup RPC_POOL_HEAT_API_CFN ${i} 8000"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep glance|while read i; do echo "bind serviceGroup RPC_POOL_GLANCE_REGISTRY ${i} 9191"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep kibana|while read i; do echo "bind serviceGroup RPC_POOL_SWIFT ${i} 8080"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep keystone|while read i; do echo "bind serviceGroup RPC_POOL_KEYSTONE_ADMIN ${i} 35357"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep kibana|while read i; do echo "bind serviceGroup RPC_POOL_KIBANA_SSL ${i} 8443"; done;
cat /etc/openstack_deploy/openstack_inventory.json | jq -r '._meta | .hostvars[] as $server | "\($server."container_name")"'|grep repo|while read i; do echo "bind serviceGroup RPC_POOL_REPO ${i} 8181"; done;

# Create VS
echo 'add lb vserver RPC_VS_GALERA TCP 172.29.236.100 3306 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_KEYSTONE_SERVICE TCP 172.29.236.100 5000 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_ELASTICSEARCH TCP 172.29.236.100 9200 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_NEUTRON_SERVER TCP 172.29.236.100 9696 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_NOVA_API_EC2 TCP 172.29.236.100 8773 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_HORIZON_SSL HTTP 172.29.236.100 443 -persistenceType NONE -Listenpolicy None -cltTimeout 180'
echo 'add lb vserver RPC_VS_HEAT_API TCP 172.29.236.100 8004 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_CINDER_API TCP 172.29.236.100 8776 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_KIBANA TCP 172.29.236.100 8888 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_NOVA_API_METADATA HTTP 172.29.236.100 8775 -persistenceType NONE -Listenpolicy None -cltTimeout 180'
echo 'add lb vserver RPC_VS_NOVA_API_OS_COMPUTE TCP 172.29.236.100 8774 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_GLANCE_API TCP 172.29.236.100 9292 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_NOVA_SPICE_CONSOLE HTTP 172.29.236.100 6082 -persistenceType NONE -Listenpolicy None -cltTimeout 180'
echo 'add lb vserver RPC_VS_HEAT_API_CLOUDWATCH TCP 172.29.236.100 8003 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_HORIZON HTTP 172.29.236.100 80 -persistenceType NONE -Listenpolicy None -cltTimeout 180'
echo 'add lb vserver RPC_VS_HEAT_API_CFN TCP 172.29.236.100 8000 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_GLANCE_REGISTRY TCP 172.29.236.100 9191 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_SWIFT HTTP 172.29.236.100 8080 -persistenceType NONE -Listenpolicy None -cltTimeout 180'
echo 'add lb vserver RPC_VS_KEYSTONE_ADMIN TCP 172.29.236.100 35357 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_KIBANA_SSL TCP 172.29.236.100 8443 -persistenceType NONE -Listenpolicy None -cltTimeout 9000'
echo 'add lb vserver RPC_VS_REPO HTTP 172.29.236.100 8181 -persistenceType NONE -Listenpolicy None -cltTimeout 180'

# Bind VS to ServiceGroup
echo 'bind lb vserver RPC_VS_HORIZON RPC_POOL_HORIZON'
echo 'bind lb vserver RPC_VS_HORIZON_SSL RPC_POOL_HORIZON_SSL'
echo 'bind lb vserver RPC_VS_KEYSTONE_SERVICE RPC_POOL_KEYSTONE_SERVICE'
echo 'bind lb vserver RPC_VS_GALERA RPC_POOL_GALERA'
echo 'bind lb vserver RPC_VS_ELASTICSEARCH RPC_POOL_ELASTICSEARCH'
echo 'bind lb vserver RPC_VS_NEUTRON_SERVER RPC_POOL_NEUTRON_SERVER'
echo 'bind lb vserver RPC_VS_NOVA_API_EC2 RPC_POOL_NOVA_API_EC2'
echo 'bind lb vserver RPC_VS_HEAT_API RPC_POOL_HEAT_API'
echo 'bind lb vserver RPC_VS_CINDER_API RPC_POOL_CINDER_API'
echo 'bind lb vserver RPC_VS_KIBANA RPC_POOL_KIBANA'
echo 'bind lb vserver RPC_VS_NOVA_API_METADATA RPC_POOL_NOVA_API_METADATA'
echo 'bind lb vserver RPC_VS_NOVA_API_OS_COMPUTE RPC_POOL_NOVA_API_OS_COMPUTE'
echo 'bind lb vserver RPC_VS_GLANCE_API RPC_POOL_GLANCE_API'
echo 'bind lb vserver RPC_VS_NOVA_SPICE_CONSOLE RPC_POOL_NOVA_SPICE_CONSOLE'
echo 'bind lb vserver RPC_VS_HEAT_API_CLOUDWATCH RPC_POOL_HEAT_API_CLOUDWATCH'
echo 'bind lb vserver RPC_VS_HEAT_API_CFN RPC_POOL_HEAT_API_CFN'
echo 'bind lb vserver RPC_VS_GLANCE_REGISTRY RPC_POOL_GLANCE_REGISTRY'
echo 'bind lb vserver RPC_VS_SWIFT RPC_POOL_SWIFT'
echo 'bind lb vserver RPC_VS_KEYSTONE_ADMIN RPC_POOL_KEYSTONE_ADMIN'
echo 'bind lb vserver RPC_VS_KIBANA_SSL RPC_POOL_KIBANA_SSL'
echo 'bind lb vserver RPC_VS_REPO RPC_POOL_REPO'
