#!/bin/bash

cat > /etc/apt/preferences <<EOF
Package: linux-generic linux-headers-generic linux-image-generic linux-restricted-modules-generic
Pin: version 3.19.0-51
Pin-Priority: 1001
EOF

apt-get remove -y linux-image-4.2.0-27-generic linux-headers-4.2.0-27-generic linux-image-extra-4.2.0-27-generic
apt-get install -y linux-image-3.19.0-51-generic linux-image-extra-3.19.0-51-generic linux-headers-3.19.0-51-generic
apt-get remove -y linux-image-4.2.0-30-generic linux-headers-4.2.0-30-generic linux-image-extra-4.2.0-30-generic
apt-get autoremove -y
update-grub
